name: MarketSim CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build
      
      - name: Configure Ninja build
        run: cmake -S . -B build -G Ninja
      
      - name: Build
        run: cmake --build build

      - name: Make
        run: ctest --test-dir build --output-on-failure